name: "Deploy to NuGet"

on:
  workflow_dispatch:
  push:
    branches:
    - main
    tags:
    - 'v*'

env:
  PROJECT_PATH: 'DapperMicroOrm/DapperMicroOrm.csproj'
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}\output
  NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'


jobs:
  deploy:
    name: 'Deploy Package'
    runs-on: 'ubuntu-latest'
    steps:
    - name: 'Install dotnet'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: 'Restore packages'
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: 'Build project'
      run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release

    - name: 'Pack project'
      run: dotnet pack ${{ env.PROJECT_PATH }} --no-restore --no-build --configuration Release --include-symbols -p:PackageVersion=${{ steps.version.outputs.version-without-v }} --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

    - name: 'Push package'
      run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}\*.nupkg -k --api-key ${{ secrets.NUGET_KEY }} -s ${{ env.NUGET_SOURCE_URL }}
    
